name: Release
on:
  push:
    tags: ['v*']
jobs:
  release:
    uses: JDE-Projects/Build-Tools/.github/workflows/release.yml@a2cb83a9459b6c357fc4f7778e8d1e99844fc8f9 # Build-Tools main (checkout v7)
    permissions:
      id-token: write
      attestations: write
      contents: write
    with:
      app_name: SimpleProjectManager
      dist_subfolder: "Simple Project Manager"
      python_version: "3.14"
      build_command: "Build_Simple_Project_Manager.bat"
      app_id: "9c6da3fc-e0ce-4e6f-9119-00efc3e4119f"
