name: Release
on:
  push:
    tags: ['v*']
jobs:
  release:
    uses: JDE-Projects/Build-Tools/.github/workflows/release.yml@e12bd20ecdf575c7bdf241c5bc6e6a1c95ffdf61 # Build-Tools main (installer support)
    permissions:
      id-token: write
      attestations: write
      contents: write
    with:
      app_name: SimpleProjectManager
      dist_subfolder: "Simple Project Manager"
      python_version: "3.14"
      build_command: "Build_Simple_Project_Manager.bat"
      app_id: "9c6da3fc-e0ce-4e6f-9119-00efc3e4119f"
